name: Go

on: push

jobs:

  build:
    env:
      GO111MODULE: on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: lint
        run: go vet .
      - run: go mod vendor

      - name: Test
        run: |
          go test -v ./... --bench=. -cover
